// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ummevejrrrkeczyclqsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtbWV2ZWpycnJrZWN6eWNscXN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODEwMDgwNzYsImV4cCI6MjA5NjU4NDA3Nn0.nzbgWQchOhEr7Z8rOTiDJcrmfR9q9tyoOLzjZwgEeC8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);